# Generated by Django 6.0 on 2026-06-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("portfolio", "0001_initial"),
        ("users", "0002_facultyprofile_hodprofile_placementofficerprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hodprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hods",
                to="academics.department",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="cgpa",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.department",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="portfolio.skill"
            ),
        ),
        migrations.AlterField(
            model_name="facultyprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faculty_members",
                to="academics.department",
            ),
        ),
    ]
