# Generated by Django 6.0 on 2026-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_hodprofile_department_studentprofile_cgpa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="codeforces",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="leetcode",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="location",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
