# Generated by Django 6.0 on 2026-06-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_facultyprofile_hodprofile_placementofficerprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "requirements",
                    models.TextField(
                        help_text="Skills, knowledge, and experience requirements"
                    ),
                ),
                ("location", models.CharField(default="On-site", max_length=100)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("internship", "Internship"),
                            ("contract", "Contract"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "salary_range",
                    models.CharField(
                        blank=True,
                        help_text="e.g. $80,000 - $100,000 or 12 LPA",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "min_cgpa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Minimum CGPA required to apply",
                        max_digits=4,
                    ),
                ),
                ("application_deadline", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="placements.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to online resume or cloud document",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("shortlisted", "Shortlisted"),
                            ("interviewing", "Interviewing"),
                            ("offered", "Offered"),
                            ("rejected", "Rejected"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("placement_officer_comments", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="users.studentprofile",
                    ),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="placements.jobposting",
                    ),
                ),
            ],
            options={
                "unique_together": {("job_posting", "student")},
            },
        ),
    ]
