# Generated by Django 6.0 on 2026-06-26 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("09:00 AM - 10:30 AM", "09:00 AM - 10:30 AM"),
                            ("10:45 AM - 12:15 PM", "10:45 AM - 12:15 PM"),
                            ("01:30 PM - 03:00 PM", "01:30 PM - 03:00 PM"),
                            ("03:15 PM - 04:45 PM", "03:15 PM - 04:45 PM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("semester", models.IntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academics.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "unique_together": {("day", "slot", "semester", "department")},
            },
        ),
    ]
