# Generated by Django 6.0 on 2026-06-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_timetableentry"),
        ("users", "0003_hodprofile_department_studentprofile_cgpa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_courses",
                to="users.facultyprofile",
            ),
        ),
    ]
