# Generated by Django 6.0 on 2026-06-29 07:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_course_faculty"),
        ("users", "0004_studentprofile_codeforces_studentprofile_github_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("activity_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logged_activities",
                        to="users.facultyprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="users.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassIncharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_incharges",
                        to="academics.department",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_incharges",
                        to="users.facultyprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("department", "semester")},
            },
        ),
    ]
